### ISSUE TITLE
the link is invalid

### ISSUE THREAD

**Issue by liujianzhao6328057** [z-bingo/awesome-image-denoising-state-of-the-art#3]
Hi,thanks for your jobs . But the link is invalid now .Could you please update the link ? Thank you very much

**Comment by z-bingo** [comment]
Project pages of some works are not found, hence, some links are invalid especially Web and Code. I will update the links if I have accessed them.

**Comment by vitorsr** [comment]
@z-bingo, you could try (at least from now on) archiving them in the [Wayback Machine (Internet Archive)](http://web.archive.org/) the first time you access the links. 😄

Suffices accessing <http://web.archive.org/save/*> (replace * for any URL). Archived copy will be available at <http://web.archive.org/*>.

For example, to archive this repository (as is)  
<http://web.archive.org/save/https://github.com/z-bingo/awesome-image-denoising-state-of-the-art>

Also works for binaries. For example, the `readme.md` of this repository
<http://web.archive.org/save/https://github.com/z-bingo/awesome-image-denoising-state-of-the-art/raw/master/readme.md>

I always do this in order to create a persistent link.

This way, even if the authors put down the links (common thing to happen because of affiliation changes), the link will be archived.

Here's an example (already archived project link for KSVD)  
<http://web.archive.org/web/20190812025943/http://www.cs.technion.ac.il/~ronrubin/software.html>  
and the zipped file with code  
<http://web.archive.org/web/20190812025943/http://www.cs.technion.ac.il/~ronrubin/Software/ksvdbox13.zip>

There's also browser extensions that add a button to do this automatically.

Cheers!

**Comment by z-bingo** [comment]
Got it, thank you.

**Comment by 491506870** [comment]
Hi, thanks for your job. Now the work "Pyramid Read Image Denoising Network (PRIDNet)" has released its code, the url is "https://github.com/491506870/PRIDNet".

**Comment by z-bingo** [comment]
Hi, you can pull a request about your work.
